language: ruby
rvm: 2.5.1
addons:
  ssh_known_hosts:
    - 93.185.103.119:2222
    - 46.101.106.19:22
    - ha1.pirati.cz:22050
    - 149.62.145.226:22050

node_js:
  - 12

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
  - bundle install --path vendor/bundle --full-index

script:
  - rm -rf _site
  - if [ "$TRAVIS_BRANCH" == "master" ]; then JEKYLL_ENV=production bundle exec jekyll build --config '_config.yml,_config.production.yml' --drafts --future; fi
  - if [ "$TRAVIS_BRANCH" == "production" ]; then JEKYLL_ENV=production bundle exec jekyll build --config '_config.yml,_config.production.yml'; fi
  - bundle exec htmlproofer --assume-extension --disable-external --url-ignore "#,#fn:1" --alt-ignore '/.*/' ./_site

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./travis/deploy.sh sandbox
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash ./travis/deploy.sh production
    on:
      branch: production

branches:
  only:
    - master
    - production

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
